[package]
name = "utf16_lit"
description = "Proc-macro to make utf-16 literals."
version = "1.0.1"
repository = "https://github.com/Lokathor/utf16_lit"
authors = ["Lokathor <zefria@gmail.com>"]
edition = "2018"
license = "Zlib OR Apache-2.0 OR MIT"

[lib]
proc-macro = true
