[package]
name = "utf16_lit"
description = "macro_rules to make utf-16 literals."
version = "2.0.2-alpha.0"
repository = "https://github.com/Lokathor/utf16_lit"
authors = ["Lokathor <zefria@gmail.com>"]
edition = "2018"
license = "Zlib OR Apache-2.0 OR MIT"
